### ISSUE TITLE
Bi-Weekly - 14.05.2024

### ISSUE THREAD

**Issue by joberkel** [bfh/opensource#136]
- Thema studentische Arbeiten HAFL -> TI
  - https://www.bfh.ch/ti/de/forschung/projektidee/
  - Erfahrungen Festanstellungen "Hilfsassistent*in" im [DSL BFH-W](https://www.bfh.ch/de/forschung/forschungsbereiche/digital-sustainability-lab/)
- Akquise Interessenten + Support für Projektideen im Bereich Autofaming
  - https://www.thethingsnetwork.org/community/Bern/#!
  - https://www.farming-hackdays.ch/
    - Hackathon-Maker anfragen/involvieren: https://hack.farming.opendata.ch/event/5
- Idee: ML TI <--> NLP BFH-W Gettogether
  - Maschinelearning-Leute departementsübergreifend vernetzen
  - Blick auf Aufbau Weiterbildungsformate, Lehre ...
- Kollaborative Online-Alternative zu Freeplane ( https://sourceforge.net/projects/freeplane/ ) für Mindmaps?
  - https://github.com/b310-digital/teammapper mal ausprobieren? @geckofarmer

**Comment by geckofarmer** [comment]
Gerade noch das gefunden für Mind map Kollaboration:
https://freeplanecollab.sourceforge.net/
