### ISSUE TITLE
Include & invite: https://bfh.science/team/about/

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/opensource#27]
# https://bfh.science

**Comment by joberkel** [comment]
Hallo Joerg

On 6/11/24 12:00, Berkel Jörg wrote:
> Wir möchten im Juli wieder ein Vor-Ort-Treffen in Bern inkl. Mittagessen machen und würden uns freuen von euch jemanden (oder auch mehrere) dabei zu haben, um uns besser BFH-weit vernetzen zu können: https://nuudel.digitalcourage.de/5xmddDZaN3SLNyRs

Da sind wir sicher gerne mit dabei, aber bis mindestens Herbst sind wir vollstaendig verplant/ueberbucht.

Wir melden uns wenn wir "bereit" sind und die weitere Planung Raum dafuer gibt.

Gruesse,
Daniel
