### ISSUE TITLE
Idea: Establish open communication channel(s)

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/opensource#51]
- [Open Source Rules of Engagement](https://waynebeaton.wordpress.com/2012/01/13/open-source-rules-of-engagement/)
 - https://opensource.guide - [Building Welcoming Communities](https://opensource.guide/building-community/#setting-your-project-up-for-success)

**Comment by Myriamwasmuth** [comment]
Kann ich schon etwas machen @MarkusTiede?

**Comment by MarkusTiede** [comment]
https://github.com/bfh/open-source/issues/60

**Comment by MarkusTiede** [comment]
# document (purpose & solution) tools used
 - [ ] BBB
 - [ ] Framadate (Nuudel)
 - [ ] keepassxc

**Comment by MarkusTiede** [comment]
Wir sollten eine Bezeichnung für unsere Community festlegen:
 - [ ] Kurzname:
 - [ ] Langname:

**Comment by MarkusTiede** [comment]
Mailing list idea: https://framalistes.org/sympa/
 - seen at: https://ospo.zone/membership/

**Comment by MarkusTiede** [comment]
- https://github.com/bfh/opensource/issues/83
