### ISSUE TITLE
Setup (public) official landing page for "Open Source @ BFH"

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/opensource#7]
# https://bfh.ch/opensource ✅

## e.g.
http://www.opensource.unibe.ch
https://opensource.zalando.com
https://opensource.ibm.com
https://opensource.redhat.com
https://opensource.microsoft.com
https://opensource.apple.com

**Comment by MarkusTiede** [comment]
# Setup
- kollaborative Inhalte (wie?!)

# Zielgruppe für die Landing-Page
## (interne) BFH Mitarbeitenden + Studierende
## (externe) Sichten (information only)

**Comment by AnniqueLombard** [comment]
Good news, die Url https: //opensource.bfh.ch ist beantragt, muss allerding vom Rektor bewilligt werden, das kann noch einige Tage dauern. 

Die Webseite ist ein "Redirect" von einer Webseite im Look der BFH, wo genau diese anzzgliedern ist, bin ich aktuell am abklären. Möglich wäre 1) Ebene BFH auf der Themenwebseite Humane Digitale Transformation (www.bfh.ch/de/strategische-themenfelder/digitalisierung/) oder 2) direkt am IPST (wo genau tbd) angesiedelt. Ich tendiere für höhere Ebene BFH, da dies ein departementsübergreifendes Projekt ist. Ich sehe aber auch praktische Vorteile wenn's beim IPST wäre.

@MarkusTiede Was scheint besser? Wir können das gerne bei Gelegenheit besprechen

**Comment by MarkusTiede** [comment]
Hallo @AnniqueLombard - super: danke für die Information; das ging ja schnell!

Ich würde es ebenfalls höher / IPST neutraler ansiedeln: Gültigkeitsbereich, Sichtbarkeit und externes Mitwirken sollte nicht "nur" auf das IPST begrenzt sein.

**Comment by AnniqueLombard** [comment]
@MarkusTiede Danke für Deine Meinung, es werden immer mehr Leute in die Anfrage involviert... aber sollte klappen. Am 10.11 habe ich eine Sitzung dazu und werde für eine Einbettung auf der Seite Humane Digitale Transformation (HDT) argumentieren. Ein Sub-Thema von HDT ist "Open Digital Knowledge", da passt es eigentlich gut rein. I keep you posted!

**Comment by MarkusTiede** [comment]
Hallo @AnniqueLombard - danke für die Information; wenn es ein Beispiel aus dem "Higher Education" Sektor braucht kannst du meiner Meinung nach gut das Wirken vom RIT (Rochester Institute of Technology) anführen:

https://todogroup.org/guides/casestudies/rit/
https://fossrit.github.io

**Comment by MarkusTiede** [comment]
My 2 cents at the moment
- [ ] remote (e.g. markdown) inclusion in our magnolia instance possible?
- [ ] when will the sub-domain be ready for redirection?
  - e.g. https://github.com/digital-sustainability/open-source/
- [ ] @MarkusTiede : Meeting to discuss draft for webpage layout

**Comment by AnniqueLombard** [comment]
@MarkusTiede: Um welche Zeit ist das Meeting am Freitag, finde keine Kalendereinladung dazu. Danke für die Info mit Link.

**Comment by MarkusTiede** [comment]
Requires #16 at the moment BFH internal processes require an actual, official existing page to link to.

**Comment by AnniqueLombard** [comment]
Update: Schlussfolgerung nach kurzem Gespräch mit Matthias: zum aktuellen Zeitpunkt würde er nicht ausführlich Rechtsabklärungen machen. Seine Einschätzung: es sollte nicht problematisch sein, eine  Verlinkung auf einen "bfh" GitHub Account zu machen.

**Comment by MarkusTiede** [comment]
- [ ] setup https://pages.github.com for BFH on top-level orga

**Comment by MarkusTiede** [comment]
# bfh.science

![image](https://user-images.githubusercontent.com/1764012/206158219-96fad8c5-a52c-4f16-9fcd-8ed1a5c1543a.png)

# https://opensource.bfh.ch

## muss offiziellen Charakter haben 
## BFH abgesegnet
## HDT als Sponsor

**Comment by AnniqueLombard** [comment]
(Entschuldigt meine Abwesenheit heute im Call, ich bin mit Kopfschmerzen und Erkältung zu Hause und habe den Morgen (inkl. Bundesratswahlen) komplett verschlafen. Wir können gerne bilateral besprechen, was gerade ansteht.)

**Comment by AnniqueLombard** [comment]
Update: Der erste Entwuf der neuen Webseite ist als Entwurf online aber noch nicht publiziert. So kommt er daher im BFH-Auftritt. Ich werde bald einen Lead-Text liefern und wünschen, dass als Kontakt Markus angegeben wird. 

Stimmt der Link zu GitHub: http://github.com/bfh/open-source 

![image](https://user-images.githubusercontent.com/116714643/206472024-01920038-3712-457a-a496-03b2cef6c6f5.png)

**Comment by AnniqueLombard** [comment]
Lieber @MarkusTiede, Könnten wir bei Gelegenheit besprechen, welche Inhalte auf dieser Landing Page künftig zusätzlich aufgeführt werden sollten? Beste Grüsse, Annique

**Comment by AnniqueLombard** [comment]
Erstellen einer e-mail Adresse: wie soll diese lauten? 
Passt: opensource@bfh.ch
oder was mit "info": info-opensource@bfh.ch 
mit Weiterleitung an Dich und mich oder wie soll das zu Beginn ablaufen?

**Comment by MarkusTiede** [comment]
Hallo @AnniqueLombard : wir hatten hierfür bereits den Issue : https://github.com/bfh/open-source/issues/15 lass uns doch gerne dort alle weiteren Details besprechen.

**Comment by AnniqueLombard** [comment]
Draft einsehbar online als Entwurf: https://cms.bfh.ch/bfh/de/ueber-die-bfh/profil-werte/open-source/ für alle BFH Mitarbeitenden. Damit könnten wir also auch Inputs von den anderen Departementen abholen.

**Comment by MarkusTiede** [comment]
Hallo @AnniqueLombard - super danke - ich bekomme wohl oben einen 403 Forbidden:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/1764012/208372754-7f267476-0e0b-46ec-bde9-cda2c1bdc9ad.png">

Lass uns gerne am Mittwoch die Seite zum Inhalt unseres Bi-Weeklies machen iO?

**Comment by AnniqueLombard** [comment]
Hi @MarkusTiede: Bist Du in dem Moment via VPN oder BFH Netz verbunden? Das ist die Bedingung, damit Magnolia angezeigt wird... klappt's so? 

Können wir gerne morgen besprechen, die Landing page.

**Comment by vgj1** [comment]
Mögliche Inhalte für die Landing Page:

Intro
- was ist OSS
- was ist die BFH Strategie

OSS verwenden
- in der Lehre (inkl. Beispiele)
- in der Forschung (inkl. Beispiele)

OSS erstellen
- in der Lehre inkl. studentische Projekte
- in der Forschung (öffentl. geförderte Projekte mit/ohne Industrie, Direktmandate etc.)

Weitere Infos zu OSS
- BFH Ansprechpersonen und allg. Email
- HowTo Mitmachen BFH CoP
- BFH-interne Linksammlung
- BFH-externe Linksammlung

**Comment by AnniqueLombard** [comment]
Wie gestern besprochen übergebe ich diesen Task an Jonas. Meine Inputs aus meiner Vorarbeit habe ich in der heutigen e-mail festgehalten.

Follow-Up: Corina Lardelli hat die BFH verlassen und Vera Baeriswyl ist die neue Ansprechperson: vera.baeriswyl@bfh.ch

Gutes Gelingen mit dem Füllen der Webseite!

**Comment by jonasbaertschi** [comment]
Entwurf für neue Landing Page ist [auf Switchdrive hier]([[url](https://drive.switch.ch/index.php/s/L7xhGRw41woiB9A)])).

**Comment by MarkusTiede** [comment]
# Top 3

**Comment by MarkusTiede** [comment]
## VLC Player

**Comment by MarkusTiede** [comment]
## GIMP

**Comment by MarkusTiede** [comment]
## Firefox

**Comment by MarkusTiede** [comment]
## Nextcloud

**Comment by MarkusTiede** [comment]
- [ ] Write testimonials per Departements

**Comment by Hannes-Ole** [comment]
## Notepad++

**Comment by Hannes-Ole** [comment]
## KeePass

**Comment by MarkusTiede** [comment]
## [ShareX](https://getsharex.com/)

**Comment by MarkusTiede** [comment]
![image](https://github.com/bfh/opensource/assets/1764012/cc60abb2-6706-4d27-a755-ebd9307e44c2)
