### ISSUE TITLE
#55 Richard Stallman Lecture @BFH 11.05.2023

### ISSUE THREAD

**Issue by AnniqueLombard** [bfh/opensource#80]
## Funnel Entry Date
2023-04

## Idea Owner
@AnniqueLombard

## Idea Description

Initiiert über Matthias Stürmer: Richard Stallman wird am 11.5. am Nachmittag in der Aula der BFH eine Lecture halten. Matthias Stürmer war in Kontakt mit den Leuten, die ihn in die Schweiz eingeladen haben. 

Wer von Seite IPST den Event unterstützt ist aktuell in Abklärung, ebenso jene vom CH Open. 
(Ich bin an dem Tag nicht anwesend (Ferienbeginn) und kann am Tag selber nichts mehr beitragen)

Frage an alle hier: 
Wie kann der Event genutzt werden für die Community? 
Welche Kommunikationsmassnahmen sind erwünscht?

**Comment by MarkusTiede** [comment]
https://www.ch-open.ch/richard-stallman-is-back-in-bern/
