### ISSUE TITLE
Leitungsgremium WWI-HAFL Slot zum Thema Open Source

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/opensource#81]
# 04.05.2023 - @Hannes-Ole 

## Impuls dafür 
war die Idee des CoP OS, dass es Departmentsspezifisch «kleinere» CoPs gibt, die das Thema OS am jeweiligen Department fortsetzen (ist schon etwas her, dass wir darüber sprachen).
 - https://github.com/bfh/opensource/issues/54
 - https://github.com/bfh/opensource/issues/50
 - beides hatte aufgrund des Aufwands geringe Prio:
   - https://github.com/bfh/opensource/issues/13#issuecomment-1411727192

## Eventuell hast du Empfehlungen / Ressourcen diesbezüglich?
   - https://github.com/bfh/opensource/issues/12
     - CoPs: https://scaledagileframework.com/communities-of-practice/
     - Format: https://opensourcefriday.com
   - copy concept der "BFH IPST Circles" - https://github.com/MyriamWasmuth
     - e.g. https://github.com/digital-sustainability/open-source-circle
     - Lead: https://github.com/MaurizioPiu
   - goal : OSPO - e.g. like http://ospo101.org 

[![](https://github.com/todogroup/ospo-career-path/raw/main/OSPO-101/module3/ospo-structure.png)](https://github.com/todogroup/ospo-career-path/blob/main/OSPO-101/module3/README.md#functions-of-an-ospo-in-the-enterprise)

### why: https://github.com/todogroup/ospo-career-path/blob/main/OSPO-101/module2/README.md#lesson-overview-of-open-source-program-office-ospo

ein paar Issues geupdatet habe – evtl. wäre es auch darüber gut zu sprechen

**Comment by Hannes-Ole** [comment]
Danke für den Input. 
Der Input wurde gut angenommen, hat jedoch auch Skepsis/Vorbehalte ggü. Open Source (und auch dem "Randthema" Open Educational Ressources) zum Vorschein gebracht (Bedenken bzgl. Autoren-Recht, Wirtschaftlichkeit, Konkurrenzfähigkeit).

Als nächster Schritt wird bei einer der nächsten Fachbereichsrats-Sitzungen das Thema angeschnitten.
