### ISSUE TITLE
Try until mid June: Setup matrix.org space and room for BFH/opensource CoP

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/opensource#83]
# https://matrix.to/#/#bfh:matrix.org

## https://matrix.to/#/#bfh-opensource-cop:matrix.org

**Comment by jonasbaertschi** [comment]
We should integrate existing Matrix instances at BFH into this instance (notably DSL's)

**Comment by MarkusTiede** [comment]
https://github.com/bfh/opensource/issues/84

**Comment by MarkusTiede** [comment]
> We should integrate existing Matrix instances at BFH into this instance (notably DSL's)

Thanks @jonasbaertschi for bringing this up - my 2 cents
- [ ] as far as I know we currently lack the federation feature of matrix with our instance
- [ ] imho the hosting scope should be similar to e.g. out nextcloud or gitlab instance(s)

**Comment by jonasbaertschi** [comment]
DSL says that integration is currently not an option because they have confidential content

**Comment by MarkusTiede** [comment]
I think we need to look into this in more detail in future: imho federation and hosting should not be a concern with respect to confidential content.

Matrix does support strong end2end encryption where necessary - as e.g. also eMail does: and e.g. we're also hosting our own, interconnected and federated servers for these service (eMail).

**Comment by dominiwe** [comment]
> DSL says that integration is currently not an option because they have confidential content

We have two instances at DSL:

- Main instance
- Staging instance

Currently only the staging instance (used for testing and bot development) has federation turned on. My current concerns for federating the main instance are:

- Users unfamiliar with Matrix create public rooms which are then accessible to anyone
- User profiles (username, avatar) will become publicly accessible

I would ideally like a way to get consent from the current users of the instance before we turn this on.

We (DSL team) have a meeting tomorrow in which we will further discuss the viability of turning on federation for the main instance.

We also have an [Element Call](https://github.com/vector-im/element-call) instance. It is a Jitsi alternative which uses the matrix protocol and encryption for video and audio calls. It is however still in beta and doesn't yet support our method of authentication.
