### ISSUE TITLE
Anfrage Beitrag für das Magazin "Präsenz"

### ISSUE THREAD

**Issue by MarkusTiede** [bfh/opensource#87]
https://www.bfh.ch/de/aktuell/magazine/praesenz/
 
Wir planen derzeit die nächste Ausgabe, die im September 2023 erscheinen soll. Das Fokusthema soll dieses Mal auf der künstlichen Intelligenz liegen. Da wurdest du mir als Fachperson für die Community of Practice Open Source ans Herz gelegt. Anscheinend gibt es dazu ja auch schon eine Website. Wäre es dir möglich, auf einer Seite zu schildern, was es damit auf sich hat? Zeichenzahl wäre 2000 inkl. Leerzeichen plus ein Bild, falls dazu ein geeignetes vorhanden wäre.

**Comment by lenatichy** [comment]
Hallo Markus, merci für die Anfrage. Mir ist noch nicht ganz klar, worum es im Artikel gehen soll - KI im Bereich Open Source, oder noch was Spezifischeres? Und könntest du mir noch sagen, auf welche Website du dich beziehst? Meinst du evtl. unsere Ressourcen zu KI in der Lehre? https://virtuelleakademie.notion.site/KI-in-der-Lehre-af068030108844c4834ef00824fd8da6

**Comment by MarkusTiede** [comment]
Die Anfrage haben wir als CoP von [Natascha Branscheidt](https://www.bfh.ch/de/ueber-die-bfh/personen/yzfvq3zb56j5/) bekommen; ich habe diese zugesagt. Die obigen Informationen stammen "einfach" aus der Anfrage.

<img width="1475" alt="image" src="https://github.com/bfh/opensource/assets/1764012/74c55598-7d5a-4031-ae38-e9d25d65eca2">

**Comment by MarkusTiede** [comment]
# Open Source @ Berner Fachhochschule

Die BFH baut eine Anlaufstelle und Informationsplattform zum Thema “Open Source” auf. Künftig können Forscher*innen und Student*innen hier - [1] - beispielsweise eine **Übersicht von geeigneten Alternativen** zu proprietärer Software finden, erfahren wie sie selber **an bestehenden, quelloffenen Projekten mitarbeiten**, oder sogar **neue eigene Projekte** in unserer Organisation - [2] - starten können.

## Four Freedoms: (1) Use, (2) Study, (3) Change and (4) Distribute

“Open Source” - noch nie gehört? Kein Problem! Im Kern ganz einfach: wenn ein digitales Gut, wie beispielsweise ein Stück Software, unter einer s.g. Open Source Lizenzen steht, hast du das Recht es **frei und kostenlos zu nutzen**. Aber nicht nur das, darüber hinaus kannst du seinen **Quellcode öffentlich einsehen und studieren**. Und noch mehr: du darfst den **Code sogar verbessern** und diese **Erweiterung wiederum verbreiten**.

Auf dieser Basis entsteht, mittlerweile seit über einem halben Jahrhundert, durch weltweite Kollaboration mitunter die beste Software die es gibt. So einfach ist das.

Und du nutzt sie bereits, ob du es weisst, willst oder nicht: ca. 80% aller modernen Softwarekomponenten und -bibliotheken sind quelloffen - im Englischen “open source”.

## Communities, Source and Practice

Vorangetrieben werden die Aktivitäten durch unsere s.g. «BFH Open Source Community of Practice» - [3] -, mit Synergien über die Departementsgrenzen hinweg: hier treffen sich bereits zu regelmässigen Bi-Weeklies das Departement “Architektur, Holz und Bau”, “Agrar-, Forst- und Lebensmittelwissenschaften”, “Technik und Informatik”, “Wirtschaft” sowie das Vizerektorat “Lehre”. Wichtig dabei ist: “nicht nur reden, sondern aktiv mit anpacken”!

## Interessiert? Dann mach mit!

Haben wir jetzt dein Interesse geweckt, dann melde dich doch gerne bei uns! Einfach eine kurze eMail an “opensource@bfh.ch” - oder möchtest du einfach mal reinschauen was wir machen und wir wir arbeiten? Nur zu gerne: wir leben “walk the talk” - alle Details zum Projekt findest du im Netz [4].
—
[1] https://bfh.ch/opensource
[2] https://github.com/bfh
[3] https://scaledagileframework.com/communities-of-practice/
[4] https://github.com/orgs/bfh/projects/1

**Comment by MarkusTiede** [comment]
Bitte eure Rückmeldungen bis spätestens Montag, 

- [ ] 31.07.2023 mit der Kommentarfunktion direkt im Dokument vermerken.
- [ ] Bitte noch eine Bildunterschrift formulieren und 
- [ ] den Verfasser (Name, Funktion) einfügen.

[139 BFH entw1_S26.pdf](https://github.com/bfh/opensource/files/12076781/139.BFH.entw1_S26.pdf)
